apiVersion: v1
kind: Service
metadata:
  name: simpleblog-postgres
  labels:
    app: simpleblog
spec:
  ports:
    - port: 5432
  selector:
    app: simpleblog
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleblog-postgres
  labels:
    app: simpleblog
spec:
  selector:
    matchLabels:
      app: simpleblog
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simpleblog
        tier: postgres
    spec:
      containers:
        - image: postgres:15
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: pg_password
            - name: POSTGRES_DB
              value: dealltask
          ports:
            - containerPort: 5432
              name: postgres
