apiVersion: v1
kind: Service
metadata:
  name: simpleblog
  labels:
    app: simpleblog
spec:
  ports:
    - port: 8888
  selector:
    app: simpleblog
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleblog
  labels:
    app: simpleblog
spec:
  selector:
    matchLabels:
      app: simpleblog
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simpleblog
        tier: backend
    spec:
      containers:
      - image: mukhlasr/simpleblog:latest
        name: simpleblog
        env: 
        - name: PGHOST
          value: simpleblog-postgres
        - name: PGDATABASE
          value: dealltask
        - name: PGSSLMODE
          value: disable
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: pg_password
        ports:
        - containerPort: 8888
          name: simpleblog
